Configuration option to override default hostname in stackdriver_agenet plugin
Stackdriver/collectd pull request #100
Opened 2017-07-16 21:47 UTC by dhrupadb

2017-07-16 21:53 UTC, igorpeshansky requested changes

2017-07-16 21:53 UTC, igorpeshansky commented on src/stackdriver_agent.c
> +      WARNING("%s: sagt_config sstrdup failed. Using defaults.",
I think you actually want to fail here, rather than silently fall back on the global hostname.

2017-07-16 22:02 UTC, dhrupadb commented on src/stackdriver_agent.c
> +      WARNING("%s: sagt_config sstrdup failed. Using defaults.",
Done. PTAL

2017-07-16 22:17 UTC, igorpeshansky requested changes

2017-07-16 22:17 UTC, igorpeshansky commented on src/stackdriver_agent.c
> +  "Hostname"
Let's add a trailing comma, for consistency.

2017-07-16 22:17 UTC, igorpeshansky commented on src/stackdriver_agent.c
> +      ERROR("%s: sagt_config sstrdup failed.",
Does this now fit on one line?

2017-07-17 18:28 UTC, dhrupadb reviewed
PTAL

2017-07-17 18:28 UTC, dhrupadb commented on src/stackdriver_agent.c
> +  "Hostname"
Done

2017-07-17 18:28 UTC, dhrupadb commented on src/stackdriver_agent.c
> +      ERROR("%s: sagt_config sstrdup failed.",
Done.

2017-07-17 18:42 UTC, igorpeshansky approved these changes
LGTM :shipit:

2017-07-17 18:53 UTC, merged

2019-04-18 23:19 UTC, igorpeshansky commented
dhrupadb was at Google at the time.