Use flags to handle error suppression from wg_curl_get_or_post.
Stackdriver/collectd pull request #116
Opened 2017-10-04 14:54 UTC by bmoyles0117

Styles are certainly off within this PR, however, I want to validate the approach before correcting style issues.

2017-10-04 16:39 UTC, dhrupadb requested changes

2017-10-04 16:39 UTC, dhrupadb commented on src/write_gcm.c
> +#define WG_CURL_FLAG_IGNORE_BUFFER_OVERFLOW 2
I would flip this. I.e. The flag should be something to the tune of `ERROR_ON_BUFFER_OVERFLOWS`. If we have a limited size buffer and a 200 response from the API doesn't fit in the buffer, I agree with Javier that that's not an error condition, but merely a constraint in our implementation. AFAIK the call to the API succeeded and the response outlines how the API handled this request in more detail. We can choose to error in case this detailed error is supposed to fit in our buffer.

2017-10-04 16:39 UTC, dhrupadb commented on src/write_gcm.c
> +      ERROR("write_gcm: wg_curl_get_or_post: The receive buffer overflowed.");
I would never ERROR here. I think this should be a WARNING log with DEBUG logging actually dumping out the entire content of the buffer each time (i.e. pull the DEBUG bit out of the conditional all together).

2017-10-04 20:10 UTC, bmoyles0117 commented on src/write_gcm.c
> +#define WG_CURL_FLAG_IGNORE_BUFFER_OVERFLOW 2
My argument against that, is that I don't want to ALWAYS ask for an error to be returned. It'd be nice of the default behavior (as it currently is), is that a downstream error gets propagated upwards. At the end of the day, I can run in either direction, but it'd be good to have a tiebreaker here.

2017-10-04 20:38 UTC, dhrupadb commented on src/write_gcm.c
> +#define WG_CURL_FLAG_IGNORE_BUFFER_OVERFLOW 2
In general I agree with you, error suppression should be the exception, not the norm. However, if I take a step back and ask myself -- is a buffer overflow really an error, based on the essence of this function? I seem to convince myself no. To extend, I don't think there're really any cases in this code where we actually want to crap out on a buffer overflow (I might be wrong), which is why I wanted to default to ignoring the error. 

This may be a non-issue if we decide to dynamically grow the buffer in the write_callback as suggested in #114.

2017-11-07 15:47 UTC, igorpeshansky requested changes

2017-11-07 15:47 UTC, igorpeshansky commented on src/write_gcm.c
> +    const char **headers, int num_headers, int flags);
Flags are generally `unsigned`.

2017-11-07 15:47 UTC, igorpeshansky commented on src/write_gcm.c
> +#define WG_CURL_FLAG_SILENT_FAILURES 1
If these are bit flags that will be or'ed, it may be preferable to use `0x01` and `0x02`.

2017-11-07 15:47 UTC, igorpeshansky commented on src/write_gcm.c
> +      ERROR("write_gcm: wg_curl_get_or_post: The receive buffer overflowed.");
+1 to both `WARNING` and dumping the buffer via `DEBUG`. I would also suggest logging this message via `DEBUG` in the `else` branch.

2017-11-07 15:47 UTC, igorpeshansky commented on src/write_gcm.c
> +  char * gcp_hostname = wg_get_from_gcp_metadata_server("instance/hostname", WG_CURL_FLAG_SILENT_FAILURES);
Reformat to fit in 80 characters? Also the next one.

2017-11-07 15:47 UTC, igorpeshansky commented on src/write_gcm.c
> +    int flags) {
Fits on the previous line, but see my other comment about the type.

2017-11-07 15:47 UTC, igorpeshansky commented on src/write_gcm.c
> +    int flags) {
Fits on the previous line, but see my other comment about the type.

2017-11-07 15:47 UTC, igorpeshansky commented on src/write_gcm.c
>        ERROR("write_gcm: wg_get_from_metadata_server failed to fetch metadata"
[Optional] Log the same message via `DEBUG` in the `else` branch.

2017-11-07 15:47 UTC, igorpeshansky commented on src/write_gcm.c
> +            headers, STATIC_ARRAY_SIZE(headers), WG_CURL_FLAG_IGNORE_BUFFER_OVERFLOW) != 0) {
Fit in 80 columns.

2019-08-12 20:54 UTC, jkohen commented
@bmoyles0117 do we still need this PR?

2019-08-13 17:58 UTC, bmoyles0117 commented
As this PR is almost 2 years old, I've lost most context. @igorpeshansky do you feel that this change is still relevant / necessary, or can we abandon?

2020-02-25 20:01 UTC, closed without merging