Regenerated autotool generated files
Stackdriver/collectd pull request #118
Opened 2017-10-05 20:56 UTC by dhrupadb

Ran `automake` and `autoconf`

2017-10-05 21:03 UTC, jkohen approved these changes
I assume you've tested this by now. Thanks for taking care of it!

2017-10-05 21:30 UTC, igorpeshansky requested changes

2017-10-05 21:30 UTC, igorpeshansky commented on configure
> +# Generated by GNU Autoconf 2.69 for collectd 5.5.2.1425.gcba3710.
Let's try to make the patch as clean as possible, please.

2017-10-05 21:45 UTC, dhrupadb commented
PTAL

2017-10-06 14:03 UTC, igorpeshansky approved these changes
LGTM :shipit:

2017-10-06 14:05 UTC, merged

2019-04-18 23:17 UTC, igorpeshansky commented
dhrupadb was at Google at the time.