Add slab metric to bytes_used memory metric
Stackdriver/collectd pull request #123
Opened 2017-11-27 22:19 UTC by dhrupadb

2017-11-27 22:57 UTC, bmoyles0117 reviewed
LGTM

2017-11-27 22:57 UTC, bmoyles0117 approved these changes
LGTM

2017-11-28 21:31 UTC, qingling128 approved these changes
LGTM.

2017-11-28 22:05 UTC, igorpeshansky requested changes
One minor thing, otherwise LGTM.

2017-11-28 22:05 UTC, igorpeshansky commented on src/memory.c
> +		               "slab",        mem_slab_total);
Let's add "slab" before "free"... Ditto below.

2017-11-29 14:37 UTC, dhrupadb reviewed
PTAL

2017-11-29 14:48 UTC, igorpeshansky approved these changes
LGTM :shipit:

2017-11-29 14:49 UTC, merged

2019-04-18 23:15 UTC, igorpeshansky commented
dhrupadb was at Google at the time.