Defork collectd
Stackdriver/collectd pull request #143
Opened 2019-01-09 15:46 UTC by nina-marie

Brings Stackdriver's collectd fork in line with the main collectd repo.

2019-01-09 18:58 UTC, jkohen approved these changes
Excellent work!

As discussed offline, I focused the review on processes.c, especially the changes against collectd HEAD (https://github.com/collectd/collectd/compare/master...Stackdriver:nina-marie-collectd)

You suggested to look at src/Makefile.am, but I can't make head or tails of it. IT's a large change, but if it works, go for it.

2019-01-09 18:58 UTC, jkohen commented on src/processes.c
> +	return (value == -1) ? 0 : value;
`-1` is used as a magic value throughout the code. Please define a constant (VALUE_UNSET?) and use it whenever these variables are initialized, set, or compared to -1 like here.

2019-01-09 18:58 UTC, jkohen commented on src/processes.c
> +        // sstrncpy(vl.type_instance, "detail", sizeof (vl.type_instance));
Please comment why this is commented out, or remove the line.

2019-01-09 18:58 UTC, jkohen commented on src/processes.c
> +    if (check_capabil
There seems to be inconsistent identation in this file (the two lines above are one instance), perhaps due to mixed usage of spaces and tabs. Can you please unify it following the upstream convention?

2019-01-09 20:14 UTC, igorpeshansky requested changes
Should we not be reviewing the diff between our current master (i.e., `stackdriver-agent-5.5.2`) and the proposed HEAD, so we know what we're picking up?
Eventually, this should be our forked changes rebased on top of the upstream `master`, and we could review that as well, but first we need to know what's changing in our copy, right?
I'd propose sitting down with @nina-marie when I'm back and rebasing these changes together.

2019-02-14 19:27 UTC, bsiegert commented
How feasible would it be to get rid of the fork altogether and have the `write_gcm` plugin (which, I gather, is what makes the stackdriver integration work at all) be a standalone repo, requiring an upstream collectd installed?

(As a packager, this would be much nicer, given that we already have a working collectd port in pkgsrc.)

2019-02-14 20:20 UTC, igorpeshansky commented
@bsiegert Unfortunately, this isn't how collectd plugins work. They are required to be built along with the collectd binary (except for some rare cases like plugins written in another language).
We've toyed with the idea of maintaining a separate repo for the `write_gcm` plugin and pulling in upstream collectd via a git submodule, but the work in this PR is a prerequisite for that happening in any case. Another possibility is to converge upstream's `write_stackdriver` and our `write_gcm` to the point where we can simply use the upstream codebase. At the moment, however, none of those are actual planned work.

2019-07-15 19:57 UTC, igorpeshansky commented
Closing in favor of #150.

2019-07-15 19:57 UTC, closed without merging