Stop poisoning function in debug mode
Stackdriver/collectd pull request #153
Opened 2019-10-09 18:32 UTC by yinzhi7

2019-10-09 18:46 UTC, qingling128 commented
Can we include the original PR that we are cherry picking? So that we have some context regarding to why this change is needed.

2019-10-09 21:43 UTC, igorpeshansky requested changes
I don't believe it's a good idea to cherry-pick this into the 5.5.2 branch. We will switch to the 5.8.1 branch at some point, which already contains this change. @qingling128, have we decided to stay with the 5.5.2 branch for long enough to justify this?

2019-10-10 03:13 UTC, qingling128 commented
@igorpeshansky - The reason we were considering this cherry pick is because this turned out to be the last blocker against Sles15 support for monitoring agent. And the content of the cherrypick did not seem harmful. As Sophie got so close to finishing this work (she shared a doc covering all the testing), wrapping it up saves us some context switch time and could benefit customers a bit earlier.

2019-10-15 03:49 UTC, qingling128 reviewed
One comment regarding to `DONT_POISON_SPRINTF_YET`.

2019-10-15 03:49 UTC, qingling128 commented on src/lua.c
The original PR also removed the `DONT_POISON_SPRINTF_YET` definition. Should we do that as well?

![image](https://user-images.githubusercontent.com/5287526/66798646-acc02480-eedc-11e9-957b-96b2cf22810b.png)

2019-10-15 15:00 UTC, sophieyfang commented on src/lua.c
Nice Catch!

2019-10-15 16:59 UTC, igorpeshansky requested changes
A couple of accidental changes from merge conflict resolution.

2019-10-15 16:59 UTC, igorpeshansky commented on src/perl.c
> +#include <stdbool.h>
This seems like an accidental change (merge conflict)... The 5.5.2 branch needs this `#if`/`#endif`.

2019-10-15 16:59 UTC, igorpeshansky commented on src/utils_lua.c
> +#include "common.h"
Same here. `common.h` is already included 2 lines below. Let's remove this line.

2019-10-15 17:22 UTC, igorpeshansky requested changes
Minor.

2019-10-15 17:22 UTC, igorpeshansky commented on src/perl.c
> +#include <stdbool.h>
[Optional] The original code had a space here. Might as well keep it consistent with the rest of the code.

2019-10-15 19:09 UTC, igorpeshansky approved these changes
LGTM :shipit:

2019-10-15 19:10 UTC, qingling128 approved these changes
LGTM

2019-10-15 19:10 UTC, merged