Extract RPC summaries from backend responses.
Stackdriver/collectd pull request #158
Opened 2019-10-30 16:25 UTC by jkohen

Implemented CreateTimeSeriesSummary parser. A follow-up change will use this to produce metrics.

2019-10-30 16:47 UTC, igorpeshansky requested changes
You may have to rebase your branch on the latest `stackdriver-agent-5.8.1` — it's still not quite stable, and underwent another rebase. It should be simple in an interactive rebase: just delete https://github.com/Stackdriver/collectd/pull/158/commits/6a0aef8032d0a191ea35bdcaec3cc5618105e76d and https://github.com/Stackdriver/collectd/pull/158/commits/8a2a4f8fab29d9cfce42d330b8ea58f6209234b8, and replay the rest of the commits.

2019-10-30 16:50 UTC, jkohen commented
> You may have to rebase your branch on the latest `stackdriver-agent-5.8.1` — it's still not quite stable, and underwent another rebase. It should be simple in an interactive rebase: just delete [6a0aef8](https://github.com/Stackdriver/collectd/commit/6a0aef8032d0a191ea35bdcaec3cc5618105e76d) and [8a2a4f8](https://github.com/Stackdriver/collectd/commit/8a2a4f8fab29d9cfce42d330b8ea58f6209234b8), and replay the rest of the commits.

Thanks for the warning. Can you provide the commands I need to run to do the rebase? Any idea when it'll become stable so that a simple `git merge` works?

2019-10-30 17:32 UTC, igorpeshansky commented
I was suggesting an [interactive rebase](https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history#interactive-rebase):
```
git fetch && git checkout stackdriver-agent-5.8.1 && git reset --hard origin/stackdriver-agent-5.8.1
git checkout rpc_response
git rebase -i stackdriver-agent-5.8.1
# In the rebase-todo, drop the first two commits with numbers 6a0aef8 and 8a2a4f8 and save.
# You should have a clean rebase at this point. Check it with:
git log rpc_response..stackdriver-agent-5.8.1  # should be empty
```
@qingling128 and I just agreed to freeze the current `stackdriver-agent-5.8.1` branch history, so this was the last rebase.

2019-10-30 17:35 UTC, bmoyles0117 commented
I'll wait for the rebase to review, apparently the DIFF shows changes that are not part of your changes. When you've done the rebase, make sure you do `git push -f` to force the push.

2019-10-30 17:38 UTC, jkohen commented
> I was suggesting an [interactive rebase](https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history#interactive-rebase):
> 
> ```
> git fetch && git checkout stackdriver-agent-5.8.1 && git reset --hard origin/stackdriver-agent-5.8.1
> git checkout rpc_response
> git rebase -i stackdriver-agent-5.8.1
> # In the rebase-todo, drop the first two commits with numbers 6a0aef8 and 8a2a4f8 and save.
> # You should have a clean rebase at this point. Check it with:
> git log rpc_response..stackdriver-agent-5.8.1  # should be empty
> ```
> 
> @qingling128 and I just agreed to freeze the current `stackdriver-agent-5.8.1` branch history, so this was the last rebase.

Done, thank you. I didn't see 8a2a4f8 though.

2019-11-01 05:49 UTC, qingling128 commented
This one seems ready for review. @bmoyles0117 @igorpeshansky

2019-11-01 16:46 UTC, bmoyles0117 commented
Reviewing now, thanks for the ping @qingling128

2019-11-05 14:37 UTC, bmoyles0117 approved these changes
LGTM, barring 2 small comments.

2019-11-05 14:37 UTC, bmoyles0117 commented on src/collectd_time_series_response_test.json
> +        "index": 0
nit: indentation seems off, can you run these files through JSON lint?

2019-11-05 14:37 UTC, bmoyles0117 commented on src/utils_stackdriver_json.c
> +static void print_context(const parse_summary_t *ctx) {
Can we rename this to debug_context or log_context? I initially thought this was being printed unconditionally.

2019-11-05 15:14 UTC, jkohen commented on src/collectd_time_series_response_test.json
> +        "index": 0
Done, with `json_pp`

2019-11-05 15:21 UTC, jkohen commented
Submitting. Thanks, Bryan!

2019-11-05 15:21 UTC, merged