Restart Consumer thread in case of non-shutdown thread exit.
Stackdriver/collectd pull request #88
Opened 2016-12-16 18:14 UTC by dhrupadb

Changed error logging for read thread. Set thread created to 0 in case of unnatural exit (e.g. OOM)

2016-12-17 16:43 UTC, rbuskens commented on src/write_gcm.c
> +    ERROR("write_gcm: Consumer thread is exiting.");
Nit: how about "is exiting" --> "unexpectedly exiting" so that a human looking at the logs easily identifies that this is not expected behavior?

2016-12-17 16:44 UTC, rbuskens commented on src/write_gcm.c
> +    WARNING("write_gcm: Consumer thread is exiting.");
Nit: how about changing the error message to make the context under which this is happening more clear? Given that the warning message is (currently) the same as the error message, users likely won't know that the conditions under which this issue is occurring are different (from the request_terminate == 0 case).

2016-12-17 17:49 UTC, dhrupadb commented on src/write_gcm.c
> +    ERROR("write_gcm: Consumer thread is exiting.");
Fixed.

2016-12-17 17:49 UTC, dhrupadb commented on src/write_gcm.c
> +    WARNING("write_gcm: Consumer thread is exiting.");
Ok so changed it to explicitly state that the agent is shitting down.

2016-12-17 22:16 UTC, rbuskens commented
LGTM.

2016-12-18 07:19 UTC, igorpeshansky requested changes

2016-12-18 07:19 UTC, igorpeshansky commented on src/write_gcm.c
> +      WARNING("write_gcm: Consumer thread is exiting due to agent shutdown.");
Just "`Consumer thread shutting down`" should be enough.

2016-12-18 07:19 UTC, igorpeshansky commented on src/write_gcm.c
> +    queue->consumer_thread_created = 0;
As we discussed, in constrained memory situations the agent will attempt to restart the thread, fail, and exit. Did we decide that this is the behavior we want?

2016-12-20 00:38 UTC, dhrupadb commented on src/write_gcm.c
> +    queue->consumer_thread_created = 0;
Marking as resolved given as we agreed that complete shutdown is preferable behavior than leaving the agent in a contradictory state.

2016-12-20 00:38 UTC, dhrupadb commented on src/write_gcm.c
> +      WARNING("write_gcm: Consumer thread is exiting due to agent shutdown.");
Done.

2016-12-20 00:38 UTC, dhrupadb commented
PTAL

2016-12-20 01:33 UTC, rbuskens commented
LGTM.

2016-12-20 15:47 UTC, igorpeshansky requested changes

2016-12-20 15:47 UTC, igorpeshansky commented on src/write_gcm.c
> +      WARNING("write_gcm: Consumer thread is shutting down.");
Indentation.

2016-12-20 15:52 UTC, dhrupadb commented on src/write_gcm.c
> +      WARNING("write_gcm: Consumer thread is shutting down.");
Done

2016-12-20 15:52 UTC, igorpeshansky approved these changes

2016-12-20 16:08 UTC, kosak commented on src/write_gcm.c
>        break;
I actually missed the original motivation for this PR. Is the thread crashing under mysterious circumstances? What are those circumstances?

But the point of these breaks is to make the code readable: to stop processing as soon as something bad happens. I think it makes for a pretty good "readability" experience. The reader can read from top to bottom without having to keep a lot of state in his/her head about what's happening. Namely if we get to this line, things are still good.

If you indeed want to somehow restart processing when something bad happens (I'm dubious but I'll go along with it for the sake of argument), the way I personally would structure the code is as follows. I'd add a higher level method that calls this method. Then if this method returns an error, the higher level method can do what it needs to to restart the thread, keep it going, whatever.

I think this accomplishes better readability than a chain of if-elses, or whatever you're proposing.

2016-12-20 16:20 UTC, igorpeshansky commented on src/write_gcm.c
>        break;
Thanks, Corey. We're trying to distinguish catastrophic failures (not enough memory to run the consumer thread) from potentially transient failures (one point couldn't be processed for some reason). In this case, changing a `break` to a `continue` should actually keep your original readability properties, but prevent the consumer thread from exiting on anything non-catastrophic. We'd still log, but if we can keep the thread going, once the memory pressure eases off, the agent should recover without the user having to restart it.

2016-12-21 22:06 UTC, dhrupadb commented on src/write_gcm.c
>      payloads = NULL;
@kosak : Corey - I was wondering if you had any specific motivation for setting the pointer to NULL as it is anyway going out of scope.?

2016-12-21 22:41 UTC, dhrupadb commented
PTAL

2016-12-22 00:24 UTC, igorpeshansky requested changes

2016-12-22 00:24 UTC, igorpeshansky commented on src/write_gcm.c
> +      // fatal. Destroy current payload and proceed to process the following.
Let's use consistent terminology:
```
// Couldn't update the counters — an error but not fatal.
// Drop the payloads on the floor and make a note of it.
```

2016-12-22 00:24 UTC, igorpeshansky commented on src/write_gcm.c
> -      wg_some_error_occured_g = 1;
Careful — this is used as a litmus test to check agent behavior in test (-T) mode. Let's leave those in (but maybe fix the typo in the name throughout).

2016-12-22 00:24 UTC, igorpeshansky commented on src/write_gcm.c
> +    queue->consumer_thread_created = 0;
Yeah, now that we terminate the thread in conditions that really are fatal, bringing down the whole agent sounds like the right thing to do.

2016-12-22 16:23 UTC, dhrupadb commented on src/write_gcm.c
> -      wg_some_error_occured_g = 1;
Fixed.

2016-12-22 17:40 UTC, igorpeshansky approved these changes

2016-12-22 17:40 UTC, igorpeshansky commented
LGTM :shipit:

2016-12-22 17:41 UTC, merged

2019-04-18 23:26 UTC, igorpeshansky commented
dhrupadb was at Google at the time.