Refactor write_gcm create monitored resource function
Stackdriver/collectd pull request #92
Opened 2017-02-13 21:25 UTC by dhrupadb

The function currently takes an argument list which is convenient when labels are known and finite. In order to support multiple labels (possibly required for container support), moved logic to a different function which takes an array argument and had the original function call it.

2017-02-13 23:40 UTC, igorpeshansky requested changes

2017-02-13 23:40 UTC, igorpeshansky commented on src/write_gcm.c
> +static monitored_resource_t *monitored_resource_create_from_field_arr(
I'm not too crazy about this name. How about `monitored_resource_create_from_array`?

2017-02-14 15:35 UTC, dhrupadb commented on src/write_gcm.c
> +static monitored_resource_t *monitored_resource_create_from_field_arr(
Done

2017-02-14 15:35 UTC, dhrupadb commented on src/write_gcm.c
> +    const char *type, const char *project_id, const char **keys,
Done.

2017-02-14 15:35 UTC, dhrupadb commented on src/write_gcm.c
> +    const char *type, const char *project_id, const char **keys,
Fixed.

2017-02-14 15:35 UTC, dhrupadb commented on src/write_gcm.c
> +
Fixed.

2017-02-14 15:35 UTC, dhrupadb commented on src/write_gcm.c
> +    const char *nextKey = keys[i];
Done.

2017-02-14 15:35 UTC, dhrupadb commented on src/write_gcm.c
> +
Fixed.

2017-02-14 15:36 UTC, dhrupadb commented on src/write_gcm.c
> +  size_t num_labels = 0;
Yes, I imagined it was just convention in case it was being in that way.

2017-02-14 15:36 UTC, dhrupadb commented on src/write_gcm.c
> +  for(i = 0; i < num_labels; i++) {
Fixed.

2017-02-14 15:36 UTC, dhrupadb reviewed
PTAL

2017-02-14 16:29 UTC, igorpeshansky requested changes

2017-02-14 16:29 UTC, igorpeshansky commented on src/write_gcm.c
> +    const char *type, const char *project_id, label_t *labels,
Want to make `labels` a const pointer as well?

2017-02-14 16:29 UTC, igorpeshansky commented on src/write_gcm.c
> +    ERROR("write_gcm: monitored_resource_create_from_field_arr: calloc failed.");
Update the function name? Here and below.

2017-02-14 16:29 UTC, igorpeshansky commented on src/write_gcm.c
> +  label_t labels[num_labels];
Let's keep the blank line between `va_end` and this declaration.

2017-02-14 16:46 UTC, dhrupadb commented
Done. PTAL

2017-02-14 16:58 UTC, igorpeshansky commented on src/write_gcm.c
> +    ERROR("write_gcm: monitored_resource_create_from_field_arr: calloc failed.");
You seem to have missed this one.

2017-02-14 17:07 UTC, dhrupadb commented
Sorry missed that one comment. PTAL.

2017-02-14 17:08 UTC, igorpeshansky commented on src/write_gcm.c
> +          "write_gcm: monitored_resource_create_from_array: calloc failed.");
Fits on one line now.

2017-02-14 17:10 UTC, dhrupadb commented on src/write_gcm.c
> +          "write_gcm: monitored_resource_create_from_array: calloc failed.");
Done

2017-02-14 17:52 UTC, igorpeshansky approved these changes

2017-02-14 17:52 UTC, igorpeshansky commented
LGTM :shipit:

2017-02-14 17:59 UTC, merged

2019-04-18 23:25 UTC, igorpeshansky commented
dhrupadb was at Google at the time.