Add hostname config option to NGINX plugin
Stackdriver/collectd pull request #97
Opened 2017-05-19 20:40 UTC by dhrupadb

2017-06-03 15:33 UTC, igorpeshansky requested changes

2017-06-03 15:33 UTC, igorpeshansky commented on src/nginx.c
> +  if (hostname != NULL) {
Simpler:
```
char *host = hostname != NULL ? hostname : hostname_g;
sstrncpy (vl.host, host, sizeof (vl.host));
```

2017-06-03 15:33 UTC, igorpeshansky commented on src/nginx.c
> +  "Hostname",
I initially said that you should also document this in `collectd.conf.pod`, but then realized that the equivalent Apache option is not documented either, so up to you. We could also fix the Apache plugin documentation, unless it's already fixed upstream.

2017-06-03 15:33 UTC, igorpeshansky commented on src/nginx.c
> +  "Hostname",
Did we not agree on `Host`, to match Apache's behavior?

2017-06-19 22:08 UTC, dhrupadb commented on src/nginx.c
> +  "Hostname",
Done.

2017-06-19 22:09 UTC, dhrupadb commented on src/nginx.c
> +  if (hostname != NULL) {
Changed. I changed the variable to host as well to keep it consistent with the config option.

2017-06-19 22:23 UTC, qingling128 commented on src/nginx.c
> +static char *host    = NULL;
Should the spacing line up with the variables below?

2017-06-19 22:52 UTC, igorpeshansky requested changes

2017-06-19 22:52 UTC, igorpeshansky commented on src/nginx.c
> +  if (strcasecmp (key, "host") == 0)
There's an opportunity for a refactoring here, but we probably want to make a minimally invasive change, so let's skip that for now.

2017-06-19 22:52 UTC, igorpeshansky commented on src/nginx.c
> +  sstrncpy (vl.host, vl_host, sizeof (vl.host));
We can combine these into one line:
```c
  sstrncpy (vl.host, host != NULL ? host : hostname_g, sizeof (vl.host));
```

2017-06-19 23:24 UTC, dhrupadb reviewed
PTAL

2017-06-19 23:24 UTC, dhrupadb commented on src/nginx.c
> +static char *host    = NULL;
Fixed

2017-06-19 23:24 UTC, dhrupadb commented on src/nginx.c
> +  if (strcasecmp (key, "host") == 0)
Agreed.

2017-06-19 23:24 UTC, dhrupadb commented on src/nginx.c
> +  sstrncpy (vl.host, vl_host, sizeof (vl.host));
Done.

2017-06-20 00:02 UTC, igorpeshansky approved these changes
LGTM :shipit:

2017-06-20 00:11 UTC, qingling128 commented
LGTM.

2017-06-20 00:14 UTC, merged

2019-04-18 23:21 UTC, igorpeshansky commented
dhrupadb was at Google at the time.